<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE lista_personas SYSTEM "lista_personas.dtd"> -->
<lista_personas>
	<persona>
		<nombre>Antonio Moreno</nombre>
		<fecha_nacimiento>27-11-2008</fecha_nacimiento>
		<sexo>Varón</sexo>
	</persona>
</lista_personas>

<!-- para hacer el dtd externo sería todo igual menos la parte de incluir el documento, que seria asi -->
<!-- <!DOCTYPE lista_personas SYSTEM "lista_personas.dtd"> -->

<!-- Elaborar el DTD dentro del documento -->

<!DOCTYPE lista_personas [
<!ELEMENT lista_personas (persona)>
<!ELEMENT persona (nombre, fecha_nacimiento, sexo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
]>

