XMLbasico_05_valida.dtd
<!ELEMENT aviso (titulo?, (parrafo+, grafico)*)>

XMLbasico_05_valida.xml
<aviso>
<titulo>...</titulo>
<parrafo>...</parrafo>
<grafico>...</grafico>
<parrafo>...</parrafo>
<grafico>...</grafico>
</aviso>

<!-- correcion -->

<!-- Falta indicar la version -->
<?xml version="1.0" encoding="UTF-8"?>
<!-- Falta incluir el DTD en el documento -->
<!DOCTYPE aviso [
<!ELEMENT aviso (titulo?, (parrafo+, grafico)*)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT parrafo (#PCDATA)>
<!ELEMENT grafico (#PCDATA)>
]>

<aviso>
<titulo>...</titulo>
<parrafo>...</parrafo>
<grafico>...</grafico>
<parrafo>...</parrafo>
<grafico>...</grafico>
</aviso>

