<!ELEMENT receta (titulo, ingredientes, procedimiento)>

<!-- XMLbasico_03_valida.xml -->
<receta>
<parrafo>Esto es un pÃ¡rrafo</parrafo>
<titulo>...</titulo>
<ingredientes>...</ingredientes>
<procedimiento>...</procedimiento>
</receta>

<!-- correcion -->

<!-- Practicamente igual que los anterires -->
<!-- Falta indicar la version -->
<?xml version="1.0" encoding="UTF-8"?>
<!-- Falta incluir el DTD en el documento -->
<!DOCTYPE receta [
<!ELEMENT receta (parrafo, titulo, ingredientes, procedimiento)>
<!ELEMENT parrafo (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT ingredientes (#PCDATA)>
<!ELEMENT procedimiento (#PCDATA)>
]>

<receta>
	<parrafo>Esto es un parrafo</parrafo>
	<titulo>...</titulo>
	<ingredientes>...</ingredientes>
	<procedimiento>...</procedimiento>
</receta>