<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE matricula SYSTEM "matricula.dtd">
<matricula>
	<personal>
		<dni>99223366M</dni>
		<nombre>Juan Pardo Martín</nombre>
		<titulacion>Ingeniería Informática</titulacion>
		<curso_academico>1997/1998</curso_academico>
		<domicilios>
			<domicilio tipo="familiar">
				<nombre1>C/ Principal nº1</nombre1>
			</domicilio>
			<domicilio tipo="habitual">
				<nombre1>C/ Secundaria nº2</nombre1>
			</domicilio>
		</domicilios>
	</personal>
	<pago>
		<tipo_matricula>Matrícula Ordinaria</tipo_matricula>
	</pago>
</matricula>

<!-- para incluir el xml y el dtd en el mismo documento solo hay que quitar el comentario de lo de abajo y ponerle comentario a la declaracion del documento de arriba -->

<!-- <!DOCTYPE matricula [
<!ELEMENT matricula (personal, pago)>
<!ELEMENT personal (dni, nombre, titulacion, curso_academico, domicilios)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT titulacion (#PCDATA)>
<!ELEMENT curso_academico (#PCDATA)>
<!ELEMENT domicilios (domicilio*)>
<!ELEMENT domicilio (nombre1)>
<!ATTLIST domicilio tipo CDATA #REQUIRED>
<!ELEMENT nombre1 (#PCDATA)>
<!ELEMENT pago (tipo_matricula)>
<!ELEMENT tipo_matricula (#PCDATA)>
]> -->



