XMLbasico_04_valida.dtd
<!ELEMENT receta (titulo, ingredientes, procedimiento)>

<!-- XMLbasico_04_valida.xml -->
<receta>
<ingredientes>...</ingredientes>
<procedimiento>...</procedimiento>
</receta>

<!-- correcion -->

<!-- Falta indicar la version -->
<?xml version="1.0" encoding="UTF-8"?>
<!-- Falta incluir el DTD en el documento -->
<!DOCTYPE receta [
<!ELEMENT receta (titulo, ingredientes, procedimiento)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT ingredientes (#PCDATA)>
<!ELEMENT procedimiento (#PCDATA)>
]>

<receta>
	<titulo>...</titulo>
	<ingredientes>...</ingredientes>
	<procedimiento>...</procedimiento>
</receta>
