=== JavierCamposCuesta/repoJavierCampos/Lenguaje de marcas/ej_DTD/ej1_DTD.dtd
<!ELEMENT tiendas (tienda*)>
<!ELEMENT tienda (nombre, direccion, distribuidor*, movil+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT distribuidor (#PCDATA)>
<!ELEMENT movil (codigo, marca, caracteristicas)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT caracteristicas (#PCDATA)>

=== JavierCamposCuesta/repoJavierCampos/Lenguaje de marcas/ej_DTD/ej1_DTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tiendas SYSTEM "ej1_DTD.dtd">
<tiendas>
  <tienda>
  	<nombre>TecnoSur</nombre>
  	<direccion>C/ Huelva, 24</direccion>
  	<distribuidor>...</distribuidor>
  	<movil>
  		<codigo>654</codigo>
  		<marca>Xiaomi</marca>
  		<caracteristicas>6Gb Ram</caracteristicas>
  	</movil>
  </tienda>
 </tiendas>
